local _init = init
local _update = update
local _uninit = uninit

function init()
	_init()
end

function update(dt)
	_update(dt)	
	
	-- Check the player's equipment slots
	local slots = 
	{ 
		"head", 
		"headCosmetic", 
		"back", 
		"backCosmetic", 
		"chest", 
		"chestCosmetic", 
		"legs", 
		"legsCosmetic" 
	}
	
	for index, slot in ipairs(slots) do
		-- Get the item descriptor object in the slot
		local item = player.equippedItem(slot)
		if item then
		
			local config = root.itemConfig(item.name)
			if config then
				config = config.config
				
				-- Conversion target variable to track our logic
				local targetItemName = nil

				-- IF: Player is Nicemice and item has a Nicemice alternative
				if config.nicemice_convertForNicemice and player.species() == "nicemice" then
					targetItemName = config.nicemice_convertForNicemice
				
				-- ELSE IF: Player is another species and item has an external species alternative
				elseif config.nicemice_otherSpeciesConversion and player.species() ~= "nicemice" then
					local currentSpecies = player.species()
					
					-- Track fallback default option
					if config.nicemice_otherSpeciesConversion["default"] then
						targetItemName = config.nicemice_otherSpeciesConversion["default"]
					end
					
					-- Override fallback if precise species key is mapped
					if config.nicemice_otherSpeciesConversion[currentSpecies] then
						targetItemName = config.nicemice_otherSpeciesConversion[currentSpecies]
					end
				end

				-- If a valid conversion path was calculated, perform the persistent swap
				if targetItemName then
					local replacementConfig = root.itemConfig(targetItemName)
					if replacementConfig then
						-- Clone the current item structure to keep parameters, directives, and counts intact
						local newItemDescriptor = {
							name = targetItemName,
							count = item.count or 1,
							parameters = item.parameters or {}
						}

						-- Safely clear custom inventoryIcon overrides generated by your tail script 
						-- so the new target armor loads its own native, default UI icon asset correctly
						if newItemDescriptor.parameters.inventoryIcon then
							newItemDescriptor.parameters.inventoryIcon = nil
						end

						player.setEquippedItem(slot, newItemDescriptor)
					end
				end

			end
		end
	end
end

function uninit()
	_uninit()
end